project_id = "xkkjjvrucnlilegwnoey"

[functions.admin_manage_users]
verify_jwt = false

[functions.admin_manage_roles]
verify_jwt = false

[functions.admin_manage_reports]
verify_jwt = false

[functions.admin_get_stats]
verify_jwt = false

[functions.create-highlight-payment]
verify_jwt = false
[functions.create-turbo-session]
verify_jwt = false

[functions.activate-turbo]
verify_jwt = false

[functions.increment-turbo-step]
verify_jwt = false
