name: Build Android App Bundle

on:
  push:
    branches: [ "main", "production" ] # Dispara em pushes para estas branches
  workflow_dispatch: # Permite disparar o build manualmente pelo painel do GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Install Dependencies
      run: npm install

    - name: Build Web Application
      run: npm run build
      env:
        # Inserir aqui variáveis de ambiente se necessárias para o build do Vite
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Sync Capacitor Android
      run: npx cap sync android

    - name: Decode Keystore
      if: env.RELEASE_KEYSTORE_BASE64 != null
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > feiraodaorca.keystore
      env:
        RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

    - name: Build Android App Bundle (.aab)
      working-directory: android
      run: |
        chmod +x gradlew
        ./gradlew bundleRelease
      env:
        # Passar os privilégios via GitHub Secrets
        ANDROID_SDK_ROOT: $ANDROID_HOME
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 7
